title: The King Group Documentation
description: Documentation for The King Group - UNDER CONSTRUCTION
theme: just-the-docs

url: http://kinggroup.northwestern.edu/documentation/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
